package:
  name: esgprep
  version: {{ environ['VERSION'] }}

source:
  git_url: git://github.com/sterlingbaldwin/esgf-prepare.git
  git_tag: {{ environ['TAG'] }}

build:
  noarch: python
  script: python setup.py install --build-for-conda
  string: {{ environ['BUILD_NAME'] }}

about:
    home: http://esgf.github.io/esgf-prepare/
    summary: Toolbox preparing your data for ESGF publication

requirements:
  build:
    - python
    - setuptools
    - pip

  run:
    - python
    - cftime
    - lockfile
    - esgf-config-parser
    - requests
    - fuzzywuzzy
    - netCDF4
    - hurry.filesize
    - treelib
