package:
  name: esgprep
  version: {{ environ['VERSION'] }}

source:
  git_url: git://github.com/sterlingbaldwin/esgf-prepare.git
  git_tag: {{ environ['TAG'] }}

build:
  script: python setup.py install
  string: {{ environ['BUILD_NAME'] }}

about:
    home: http://esgf.github.io/esgf-prepare/
    summary: Toolbox preparing your data for ESGF publication

requirements:
  build:
    - python
    - setuptools
    - pip
  
  run:
    - python
    - lockfile==0.12.2
    - esgconfigparser==0.1.17
    - requests==2.19.1
    - fuzzywuzzy==0.16.0
    - netCDF4==1.4.0
    - hurry.filesize==0.9
    - treelib==1.4.0